### ISSUE TITLE
您好 部署问题请教一下

### ISSUE THREAD

**Issue by lovezm** [blogwy/Wedding-invitation#1]
为什么部署后 数据集也弄好了 但是没有加载

**Comment by lovezm** [comment]
解决了 不过顺便问一下个人小程序能发布这个邀请函吗。似乎没办法，该选什么类目？

**Comment by blogwy** [comment]
> 解决了 不过顺便问一下个人小程序能发布这个邀请函吗。似乎没办法，该选什么类目？

生活 - 婚庆服务 试试
